/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingPagesRouteImport } from './routes/landing-pages'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DsaCrmRouteImport } from './routes/dsa-crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TTenantSlugRouteImport } from './routes/t.$tenantSlug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PortalTenantSlugRouteImport } from './routes/portal.$tenantSlug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as IndustriesGroupRouteImport } from './routes/industries.$group'
import { Route as CampaignSlugRouteImport } from './routes/campaign.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedWebhookSettingsRouteImport } from './routes/_authenticated/webhook-settings'
import { Route as AuthenticatedWebhookDeadLetterRouteImport } from './routes/_authenticated/webhook-dead-letter'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTenantPortalRouteImport } from './routes/_authenticated/tenant-portal'
import { Route as AuthenticatedTenantDashboardRouteImport } from './routes/_authenticated/tenant-dashboard'
import { Route as AuthenticatedTenantBillingRouteImport } from './routes/_authenticated/tenant-billing'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsTenantsRouteImport } from './routes/_authenticated/settings-tenants'
import { Route as AuthenticatedSettingsPlansRouteImport } from './routes/_authenticated/settings-plans'
import { Route as AuthenticatedSettingsPackRouteImport } from './routes/_authenticated/settings-pack'
import { Route as AuthenticatedSettingsCmsRouteImport } from './routes/_authenticated/settings-cms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRealestateRouteImport } from './routes/_authenticated/realestate'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedProductsalesRouteImport } from './routes/_authenticated/productsales'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPayoutHistoryRouteImport } from './routes/_authenticated/payout-history'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLeadSourcesRouteImport } from './routes/_authenticated/lead-sources'
import { Route as AuthenticatedLandingConversionsRouteImport } from './routes/_authenticated/landing-conversions'
import { Route as AuthenticatedLandingAnalyticsRouteImport } from './routes/_authenticated/landing-analytics'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated/it'
import { Route as AuthenticatedInboundRouteImport } from './routes/_authenticated/inbound'
import { Route as AuthenticatedFintechRouteImport } from './routes/_authenticated/fintech'
import { Route as AuthenticatedFeatureMatrixRouteImport } from './routes/_authenticated/feature-matrix'
import { Route as AuthenticatedDigiverifyRouteImport } from './routes/_authenticated/digiverify'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedChooseIndustryRouteImport } from './routes/_authenticated/choose-industry'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAffiliatesRouteImport } from './routes/_authenticated/affiliates'
import { Route as AuthenticatedAdminPacksRouteImport } from './routes/_authenticated/admin-packs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as IndustriesGroupIndexRouteImport } from './routes/industries.$group.index'
import { Route as AuthenticatedRealestateIndexRouteImport } from './routes/_authenticated/realestate.index'
import { Route as AuthenticatedProductsalesIndexRouteImport } from './routes/_authenticated/productsales.index'
import { Route as AuthenticatedPacksIndexRouteImport } from './routes/_authenticated/packs.index'
import { Route as AuthenticatedItIndexRouteImport } from './routes/_authenticated/it.index'
import { Route as AuthenticatedFintechIndexRouteImport } from './routes/_authenticated/fintech.index'
import { Route as IndustriesGroupSlugRouteImport } from './routes/industries.$group.$slug'
import { Route as ApiPublicRolePdfRouteImport } from './routes/api/public/role-pdf'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets_.$id'
import { Route as AuthenticatedRealestatePropertiesRouteImport } from './routes/_authenticated/realestate.properties'
import { Route as AuthenticatedRealestatePipelineRouteImport } from './routes/_authenticated/realestate.pipeline'
import { Route as AuthenticatedRealestateClientsRouteImport } from './routes/_authenticated/realestate.clients'
import { Route as AuthenticatedProductsalesProductsRouteImport } from './routes/_authenticated/productsales.products'
import { Route as AuthenticatedProductsalesOrdersRouteImport } from './routes/_authenticated/productsales.orders'
import { Route as AuthenticatedProductsalesCommissionsRouteImport } from './routes/_authenticated/productsales.commissions'
import { Route as AuthenticatedItTicketsRouteImport } from './routes/_authenticated/it.tickets'
import { Route as AuthenticatedItProjectsRouteImport } from './routes/_authenticated/it.projects'
import { Route as AuthenticatedItPipelineRouteImport } from './routes/_authenticated/it.pipeline'
import { Route as AuthenticatedIndustrySlugRouteImport } from './routes/_authenticated/industry.$slug'
import { Route as AuthenticatedFintechPipelineRouteImport } from './routes/_authenticated/fintech.pipeline'
import { Route as AuthenticatedFintechLendersRouteImport } from './routes/_authenticated/fintech.lenders'
import { Route as AuthenticatedFintechCommissionsRouteImport } from './routes/_authenticated/fintech.commissions'
import { Route as AuthenticatedFintechApplicationsRouteImport } from './routes/_authenticated/fintech.applications'
import { Route as AuthenticatedIndustrySlugIndexRouteImport } from './routes/_authenticated/industry.$slug.index'
import { Route as PortalApplyGroupSlugRouteImport } from './routes/portal.apply.$group.$slug'
import { Route as AuthenticatedPacksGroupSlugRouteImport } from './routes/_authenticated/packs.$group.$slug'
import { Route as AuthenticatedIndustrySlugSectionRouteImport } from './routes/_authenticated/industry.$slug.$section'
import { Route as AuthenticatedAffiliatesIdReferralsRouteImport } from './routes/_authenticated/affiliates_.$id.referrals'
import { Route as ApiPublicInboundMetaTenantSlugRouteImport } from './routes/api/public/inbound.meta.$tenantSlug'
import { Route as ApiPublicInboundLeadsTenantSlugRouteImport } from './routes/api/public/inbound.leads.$tenantSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPagesRoute = LandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaCrmRoute = DsaCrmRouteImport.update({
  id: '/dsa-crm',
  path: '/dsa-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugRoute = TTenantSlugRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const PortalTenantSlugRoute = PortalTenantSlugRouteImport.update({
  id: '/portal/$tenantSlug',
  path: '/portal/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesGroupRoute = IndustriesGroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => IndustriesRoute,
} as any)
const CampaignSlugRoute = CampaignSlugRouteImport.update({
  id: '/campaign/$slug',
  path: '/campaign/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebhookSettingsRoute =
  AuthenticatedWebhookSettingsRouteImport.update({
    id: '/webhook-settings',
    path: '/webhook-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhookDeadLetterRoute =
  AuthenticatedWebhookDeadLetterRouteImport.update({
    id: '/webhook-dead-letter',
    path: '/webhook-dead-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantPortalRoute =
  AuthenticatedTenantPortalRouteImport.update({
    id: '/tenant-portal',
    path: '/tenant-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantDashboardRoute =
  AuthenticatedTenantDashboardRouteImport.update({
    id: '/tenant-dashboard',
    path: '/tenant-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantBillingRoute =
  AuthenticatedTenantBillingRouteImport.update({
    id: '/tenant-billing',
    path: '/tenant-billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsTenantsRoute =
  AuthenticatedSettingsTenantsRouteImport.update({
    id: '/settings-tenants',
    path: '/settings-tenants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPlansRoute =
  AuthenticatedSettingsPlansRouteImport.update({
    id: '/settings-plans',
    path: '/settings-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPackRoute =
  AuthenticatedSettingsPackRouteImport.update({
    id: '/settings-pack',
    path: '/settings-pack',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCmsRoute =
  AuthenticatedSettingsCmsRouteImport.update({
    id: '/settings-cms',
    path: '/settings-cms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealestateRoute = AuthenticatedRealestateRouteImport.update({
  id: '/realestate',
  path: '/realestate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsalesRoute =
  AuthenticatedProductsalesRouteImport.update({
    id: '/productsales',
    path: '/productsales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutHistoryRoute =
  AuthenticatedPayoutHistoryRouteImport.update({
    id: '/payout-history',
    path: '/payout-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadSourcesRoute =
  AuthenticatedLeadSourcesRouteImport.update({
    id: '/lead-sources',
    path: '/lead-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingConversionsRoute =
  AuthenticatedLandingConversionsRouteImport.update({
    id: '/landing-conversions',
    path: '/landing-conversions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingAnalyticsRoute =
  AuthenticatedLandingAnalyticsRouteImport.update({
    id: '/landing-analytics',
    path: '/landing-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboundRoute = AuthenticatedInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFintechRoute = AuthenticatedFintechRouteImport.update({
  id: '/fintech',
  path: '/fintech',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeatureMatrixRoute =
  AuthenticatedFeatureMatrixRouteImport.update({
    id: '/feature-matrix',
    path: '/feature-matrix',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDigiverifyRoute = AuthenticatedDigiverifyRouteImport.update({
  id: '/digiverify',
  path: '/digiverify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChooseIndustryRoute =
  AuthenticatedChooseIndustryRouteImport.update({
    id: '/choose-industry',
    path: '/choose-industry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliatesRoute = AuthenticatedAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPacksRoute = AuthenticatedAdminPacksRouteImport.update({
  id: '/admin-packs',
  path: '/admin-packs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const IndustriesGroupIndexRoute = IndustriesGroupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesGroupRoute,
} as any)
const AuthenticatedRealestateIndexRoute =
  AuthenticatedRealestateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRealestateRoute,
  } as any)
const AuthenticatedProductsalesIndexRoute =
  AuthenticatedProductsalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsalesRoute,
  } as any)
const AuthenticatedPacksIndexRoute = AuthenticatedPacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItIndexRoute = AuthenticatedItIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedFintechIndexRoute =
  AuthenticatedFintechIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFintechRoute,
  } as any)
const IndustriesGroupSlugRoute = IndustriesGroupSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesGroupRoute,
} as any)
const ApiPublicRolePdfRoute = ApiPublicRolePdfRouteImport.update({
  id: '/api/public/role-pdf',
  path: '/api/public/role-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/tickets_/$id',
  path: '/tickets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealestatePropertiesRoute =
  AuthenticatedRealestatePropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedRealestateRoute,
  } as any)
const AuthenticatedRealestatePipelineRoute =
  AuthenticatedRealestatePipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedRealestateRoute,
  } as any)
const AuthenticatedRealestateClientsRoute =
  AuthenticatedRealestateClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedRealestateRoute,
  } as any)
const AuthenticatedProductsalesProductsRoute =
  AuthenticatedProductsalesProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedProductsalesRoute,
  } as any)
const AuthenticatedProductsalesOrdersRoute =
  AuthenticatedProductsalesOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedProductsalesRoute,
  } as any)
const AuthenticatedProductsalesCommissionsRoute =
  AuthenticatedProductsalesCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedProductsalesRoute,
  } as any)
const AuthenticatedItTicketsRoute = AuthenticatedItTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedItProjectsRoute = AuthenticatedItProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedItPipelineRoute = AuthenticatedItPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedIndustrySlugRoute =
  AuthenticatedIndustrySlugRouteImport.update({
    id: '/industry/$slug',
    path: '/industry/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFintechPipelineRoute =
  AuthenticatedFintechPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedFintechRoute,
  } as any)
const AuthenticatedFintechLendersRoute =
  AuthenticatedFintechLendersRouteImport.update({
    id: '/lenders',
    path: '/lenders',
    getParentRoute: () => AuthenticatedFintechRoute,
  } as any)
const AuthenticatedFintechCommissionsRoute =
  AuthenticatedFintechCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedFintechRoute,
  } as any)
const AuthenticatedFintechApplicationsRoute =
  AuthenticatedFintechApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedFintechRoute,
  } as any)
const AuthenticatedIndustrySlugIndexRoute =
  AuthenticatedIndustrySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIndustrySlugRoute,
  } as any)
const PortalApplyGroupSlugRoute = PortalApplyGroupSlugRouteImport.update({
  id: '/portal/apply/$group/$slug',
  path: '/portal/apply/$group/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPacksGroupSlugRoute =
  AuthenticatedPacksGroupSlugRouteImport.update({
    id: '/packs/$group/$slug',
    path: '/packs/$group/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustrySlugSectionRoute =
  AuthenticatedIndustrySlugSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedIndustrySlugRoute,
  } as any)
const AuthenticatedAffiliatesIdReferralsRoute =
  AuthenticatedAffiliatesIdReferralsRouteImport.update({
    id: '/affiliates_/$id/referrals',
    path: '/affiliates/$id/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicInboundMetaTenantSlugRoute =
  ApiPublicInboundMetaTenantSlugRouteImport.update({
    id: '/api/public/inbound/meta/$tenantSlug',
    path: '/api/public/inbound/meta/$tenantSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInboundLeadsTenantSlugRoute =
  ApiPublicInboundLeadsTenantSlugRouteImport.update({
    id: '/api/public/inbound/leads/$tenantSlug',
    path: '/api/public/inbound/leads/$tenantSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dsa-crm': typeof DsaCrmRoute
  '/features': typeof FeaturesRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/landing-pages': typeof LandingPagesRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-packs': typeof AuthenticatedAdminPacksRoute
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/ai': typeof AuthenticatedAiRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/choose-industry': typeof AuthenticatedChooseIndustryRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digiverify': typeof AuthenticatedDigiverifyRoute
  '/feature-matrix': typeof AuthenticatedFeatureMatrixRoute
  '/fintech': typeof AuthenticatedFintechRouteWithChildren
  '/inbound': typeof AuthenticatedInboundRoute
  '/it': typeof AuthenticatedItRouteWithChildren
  '/landing-analytics': typeof AuthenticatedLandingAnalyticsRoute
  '/landing-conversions': typeof AuthenticatedLandingConversionsRoute
  '/lead-sources': typeof AuthenticatedLeadSourcesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/payout-history': typeof AuthenticatedPayoutHistoryRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/productsales': typeof AuthenticatedProductsalesRouteWithChildren
  '/proposals': typeof AuthenticatedProposalsRoute
  '/realestate': typeof AuthenticatedRealestateRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settings-cms': typeof AuthenticatedSettingsCmsRoute
  '/settings-pack': typeof AuthenticatedSettingsPackRoute
  '/settings-plans': typeof AuthenticatedSettingsPlansRoute
  '/settings-tenants': typeof AuthenticatedSettingsTenantsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/tenant-billing': typeof AuthenticatedTenantBillingRoute
  '/tenant-dashboard': typeof AuthenticatedTenantDashboardRoute
  '/tenant-portal': typeof AuthenticatedTenantPortalRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/webhook-dead-letter': typeof AuthenticatedWebhookDeadLetterRoute
  '/webhook-settings': typeof AuthenticatedWebhookSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/industries/$group': typeof IndustriesGroupRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/portal/$tenantSlug': typeof PortalTenantSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/t/$tenantSlug': typeof TTenantSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/fintech/applications': typeof AuthenticatedFintechApplicationsRoute
  '/fintech/commissions': typeof AuthenticatedFintechCommissionsRoute
  '/fintech/lenders': typeof AuthenticatedFintechLendersRoute
  '/fintech/pipeline': typeof AuthenticatedFintechPipelineRoute
  '/industry/$slug': typeof AuthenticatedIndustrySlugRouteWithChildren
  '/it/pipeline': typeof AuthenticatedItPipelineRoute
  '/it/projects': typeof AuthenticatedItProjectsRoute
  '/it/tickets': typeof AuthenticatedItTicketsRoute
  '/productsales/commissions': typeof AuthenticatedProductsalesCommissionsRoute
  '/productsales/orders': typeof AuthenticatedProductsalesOrdersRoute
  '/productsales/products': typeof AuthenticatedProductsalesProductsRoute
  '/realestate/clients': typeof AuthenticatedRealestateClientsRoute
  '/realestate/pipeline': typeof AuthenticatedRealestatePipelineRoute
  '/realestate/properties': typeof AuthenticatedRealestatePropertiesRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/api/public/role-pdf': typeof ApiPublicRolePdfRoute
  '/industries/$group/$slug': typeof IndustriesGroupSlugRoute
  '/fintech/': typeof AuthenticatedFintechIndexRoute
  '/it/': typeof AuthenticatedItIndexRoute
  '/packs/': typeof AuthenticatedPacksIndexRoute
  '/productsales/': typeof AuthenticatedProductsalesIndexRoute
  '/realestate/': typeof AuthenticatedRealestateIndexRoute
  '/industries/$group/': typeof IndustriesGroupIndexRoute
  '/affiliates/$id/referrals': typeof AuthenticatedAffiliatesIdReferralsRoute
  '/industry/$slug/$section': typeof AuthenticatedIndustrySlugSectionRoute
  '/packs/$group/$slug': typeof AuthenticatedPacksGroupSlugRoute
  '/portal/apply/$group/$slug': typeof PortalApplyGroupSlugRoute
  '/industry/$slug/': typeof AuthenticatedIndustrySlugIndexRoute
  '/api/public/inbound/leads/$tenantSlug': typeof ApiPublicInboundLeadsTenantSlugRoute
  '/api/public/inbound/meta/$tenantSlug': typeof ApiPublicInboundMetaTenantSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dsa-crm': typeof DsaCrmRoute
  '/features': typeof FeaturesRoute
  '/landing-pages': typeof LandingPagesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-packs': typeof AuthenticatedAdminPacksRoute
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/ai': typeof AuthenticatedAiRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/choose-industry': typeof AuthenticatedChooseIndustryRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digiverify': typeof AuthenticatedDigiverifyRoute
  '/feature-matrix': typeof AuthenticatedFeatureMatrixRoute
  '/inbound': typeof AuthenticatedInboundRoute
  '/landing-analytics': typeof AuthenticatedLandingAnalyticsRoute
  '/landing-conversions': typeof AuthenticatedLandingConversionsRoute
  '/lead-sources': typeof AuthenticatedLeadSourcesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/payout-history': typeof AuthenticatedPayoutHistoryRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settings-cms': typeof AuthenticatedSettingsCmsRoute
  '/settings-pack': typeof AuthenticatedSettingsPackRoute
  '/settings-plans': typeof AuthenticatedSettingsPlansRoute
  '/settings-tenants': typeof AuthenticatedSettingsTenantsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/tenant-billing': typeof AuthenticatedTenantBillingRoute
  '/tenant-dashboard': typeof AuthenticatedTenantDashboardRoute
  '/tenant-portal': typeof AuthenticatedTenantPortalRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/webhook-dead-letter': typeof AuthenticatedWebhookDeadLetterRoute
  '/webhook-settings': typeof AuthenticatedWebhookSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/portal/$tenantSlug': typeof PortalTenantSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/t/$tenantSlug': typeof TTenantSlugRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/fintech/applications': typeof AuthenticatedFintechApplicationsRoute
  '/fintech/commissions': typeof AuthenticatedFintechCommissionsRoute
  '/fintech/lenders': typeof AuthenticatedFintechLendersRoute
  '/fintech/pipeline': typeof AuthenticatedFintechPipelineRoute
  '/it/pipeline': typeof AuthenticatedItPipelineRoute
  '/it/projects': typeof AuthenticatedItProjectsRoute
  '/it/tickets': typeof AuthenticatedItTicketsRoute
  '/productsales/commissions': typeof AuthenticatedProductsalesCommissionsRoute
  '/productsales/orders': typeof AuthenticatedProductsalesOrdersRoute
  '/productsales/products': typeof AuthenticatedProductsalesProductsRoute
  '/realestate/clients': typeof AuthenticatedRealestateClientsRoute
  '/realestate/pipeline': typeof AuthenticatedRealestatePipelineRoute
  '/realestate/properties': typeof AuthenticatedRealestatePropertiesRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/api/public/role-pdf': typeof ApiPublicRolePdfRoute
  '/industries/$group/$slug': typeof IndustriesGroupSlugRoute
  '/fintech': typeof AuthenticatedFintechIndexRoute
  '/it': typeof AuthenticatedItIndexRoute
  '/packs': typeof AuthenticatedPacksIndexRoute
  '/productsales': typeof AuthenticatedProductsalesIndexRoute
  '/realestate': typeof AuthenticatedRealestateIndexRoute
  '/industries/$group': typeof IndustriesGroupIndexRoute
  '/affiliates/$id/referrals': typeof AuthenticatedAffiliatesIdReferralsRoute
  '/industry/$slug/$section': typeof AuthenticatedIndustrySlugSectionRoute
  '/packs/$group/$slug': typeof AuthenticatedPacksGroupSlugRoute
  '/portal/apply/$group/$slug': typeof PortalApplyGroupSlugRoute
  '/industry/$slug': typeof AuthenticatedIndustrySlugIndexRoute
  '/api/public/inbound/leads/$tenantSlug': typeof ApiPublicInboundLeadsTenantSlugRoute
  '/api/public/inbound/meta/$tenantSlug': typeof ApiPublicInboundMetaTenantSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dsa-crm': typeof DsaCrmRoute
  '/features': typeof FeaturesRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/landing-pages': typeof LandingPagesRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-packs': typeof AuthenticatedAdminPacksRoute
  '/_authenticated/affiliates': typeof AuthenticatedAffiliatesRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/choose-industry': typeof AuthenticatedChooseIndustryRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/digiverify': typeof AuthenticatedDigiverifyRoute
  '/_authenticated/feature-matrix': typeof AuthenticatedFeatureMatrixRoute
  '/_authenticated/fintech': typeof AuthenticatedFintechRouteWithChildren
  '/_authenticated/inbound': typeof AuthenticatedInboundRoute
  '/_authenticated/it': typeof AuthenticatedItRouteWithChildren
  '/_authenticated/landing-analytics': typeof AuthenticatedLandingAnalyticsRoute
  '/_authenticated/landing-conversions': typeof AuthenticatedLandingConversionsRoute
  '/_authenticated/lead-sources': typeof AuthenticatedLeadSourcesRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/payout-history': typeof AuthenticatedPayoutHistoryRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/productsales': typeof AuthenticatedProductsalesRouteWithChildren
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/realestate': typeof AuthenticatedRealestateRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/settings-cms': typeof AuthenticatedSettingsCmsRoute
  '/_authenticated/settings-pack': typeof AuthenticatedSettingsPackRoute
  '/_authenticated/settings-plans': typeof AuthenticatedSettingsPlansRoute
  '/_authenticated/settings-tenants': typeof AuthenticatedSettingsTenantsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/tenant-billing': typeof AuthenticatedTenantBillingRoute
  '/_authenticated/tenant-dashboard': typeof AuthenticatedTenantDashboardRoute
  '/_authenticated/tenant-portal': typeof AuthenticatedTenantPortalRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/webhook-dead-letter': typeof AuthenticatedWebhookDeadLetterRoute
  '/_authenticated/webhook-settings': typeof AuthenticatedWebhookSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/industries/$group': typeof IndustriesGroupRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/portal/$tenantSlug': typeof PortalTenantSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/t/$tenantSlug': typeof TTenantSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/fintech/applications': typeof AuthenticatedFintechApplicationsRoute
  '/_authenticated/fintech/commissions': typeof AuthenticatedFintechCommissionsRoute
  '/_authenticated/fintech/lenders': typeof AuthenticatedFintechLendersRoute
  '/_authenticated/fintech/pipeline': typeof AuthenticatedFintechPipelineRoute
  '/_authenticated/industry/$slug': typeof AuthenticatedIndustrySlugRouteWithChildren
  '/_authenticated/it/pipeline': typeof AuthenticatedItPipelineRoute
  '/_authenticated/it/projects': typeof AuthenticatedItProjectsRoute
  '/_authenticated/it/tickets': typeof AuthenticatedItTicketsRoute
  '/_authenticated/productsales/commissions': typeof AuthenticatedProductsalesCommissionsRoute
  '/_authenticated/productsales/orders': typeof AuthenticatedProductsalesOrdersRoute
  '/_authenticated/productsales/products': typeof AuthenticatedProductsalesProductsRoute
  '/_authenticated/realestate/clients': typeof AuthenticatedRealestateClientsRoute
  '/_authenticated/realestate/pipeline': typeof AuthenticatedRealestatePipelineRoute
  '/_authenticated/realestate/properties': typeof AuthenticatedRealestatePropertiesRoute
  '/_authenticated/tickets_/$id': typeof AuthenticatedTicketsIdRoute
  '/api/public/role-pdf': typeof ApiPublicRolePdfRoute
  '/industries/$group/$slug': typeof IndustriesGroupSlugRoute
  '/_authenticated/fintech/': typeof AuthenticatedFintechIndexRoute
  '/_authenticated/it/': typeof AuthenticatedItIndexRoute
  '/_authenticated/packs/': typeof AuthenticatedPacksIndexRoute
  '/_authenticated/productsales/': typeof AuthenticatedProductsalesIndexRoute
  '/_authenticated/realestate/': typeof AuthenticatedRealestateIndexRoute
  '/industries/$group/': typeof IndustriesGroupIndexRoute
  '/_authenticated/affiliates_/$id/referrals': typeof AuthenticatedAffiliatesIdReferralsRoute
  '/_authenticated/industry/$slug/$section': typeof AuthenticatedIndustrySlugSectionRoute
  '/_authenticated/packs/$group/$slug': typeof AuthenticatedPacksGroupSlugRoute
  '/portal/apply/$group/$slug': typeof PortalApplyGroupSlugRoute
  '/_authenticated/industry/$slug/': typeof AuthenticatedIndustrySlugIndexRoute
  '/api/public/inbound/leads/$tenantSlug': typeof ApiPublicInboundLeadsTenantSlugRoute
  '/api/public/inbound/meta/$tenantSlug': typeof ApiPublicInboundMetaTenantSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/contact'
    | '/dsa-crm'
    | '/features'
    | '/industries'
    | '/landing-pages'
    | '/pricing'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-packs'
    | '/affiliates'
    | '/ai'
    | '/audit-logs'
    | '/automation'
    | '/calendar'
    | '/choose-industry'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/digiverify'
    | '/feature-matrix'
    | '/fintech'
    | '/inbound'
    | '/it'
    | '/landing-analytics'
    | '/landing-conversions'
    | '/lead-sources'
    | '/leads'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/partner'
    | '/payout-history'
    | '/pipeline'
    | '/portal'
    | '/productsales'
    | '/proposals'
    | '/realestate'
    | '/reports'
    | '/settings'
    | '/settings-cms'
    | '/settings-pack'
    | '/settings-plans'
    | '/settings-tenants'
    | '/tasks'
    | '/tenant-billing'
    | '/tenant-dashboard'
    | '/tenant-portal'
    | '/tickets'
    | '/webhook-dead-letter'
    | '/webhook-settings'
    | '/blog/$slug'
    | '/campaign/$slug'
    | '/industries/$group'
    | '/p/$slug'
    | '/portal/$tenantSlug'
    | '/products/$slug'
    | '/t/$tenantSlug'
    | '/blog/'
    | '/industries/'
    | '/products/'
    | '/fintech/applications'
    | '/fintech/commissions'
    | '/fintech/lenders'
    | '/fintech/pipeline'
    | '/industry/$slug'
    | '/it/pipeline'
    | '/it/projects'
    | '/it/tickets'
    | '/productsales/commissions'
    | '/productsales/orders'
    | '/productsales/products'
    | '/realestate/clients'
    | '/realestate/pipeline'
    | '/realestate/properties'
    | '/tickets/$id'
    | '/api/public/role-pdf'
    | '/industries/$group/$slug'
    | '/fintech/'
    | '/it/'
    | '/packs/'
    | '/productsales/'
    | '/realestate/'
    | '/industries/$group/'
    | '/affiliates/$id/referrals'
    | '/industry/$slug/$section'
    | '/packs/$group/$slug'
    | '/portal/apply/$group/$slug'
    | '/industry/$slug/'
    | '/api/public/inbound/leads/$tenantSlug'
    | '/api/public/inbound/meta/$tenantSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/contact'
    | '/dsa-crm'
    | '/features'
    | '/landing-pages'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-packs'
    | '/affiliates'
    | '/ai'
    | '/audit-logs'
    | '/automation'
    | '/calendar'
    | '/choose-industry'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/digiverify'
    | '/feature-matrix'
    | '/inbound'
    | '/landing-analytics'
    | '/landing-conversions'
    | '/lead-sources'
    | '/leads'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/partner'
    | '/payout-history'
    | '/pipeline'
    | '/portal'
    | '/proposals'
    | '/reports'
    | '/settings'
    | '/settings-cms'
    | '/settings-pack'
    | '/settings-plans'
    | '/settings-tenants'
    | '/tasks'
    | '/tenant-billing'
    | '/tenant-dashboard'
    | '/tenant-portal'
    | '/tickets'
    | '/webhook-dead-letter'
    | '/webhook-settings'
    | '/blog/$slug'
    | '/campaign/$slug'
    | '/p/$slug'
    | '/portal/$tenantSlug'
    | '/products/$slug'
    | '/t/$tenantSlug'
    | '/blog'
    | '/industries'
    | '/products'
    | '/fintech/applications'
    | '/fintech/commissions'
    | '/fintech/lenders'
    | '/fintech/pipeline'
    | '/it/pipeline'
    | '/it/projects'
    | '/it/tickets'
    | '/productsales/commissions'
    | '/productsales/orders'
    | '/productsales/products'
    | '/realestate/clients'
    | '/realestate/pipeline'
    | '/realestate/properties'
    | '/tickets/$id'
    | '/api/public/role-pdf'
    | '/industries/$group/$slug'
    | '/fintech'
    | '/it'
    | '/packs'
    | '/productsales'
    | '/realestate'
    | '/industries/$group'
    | '/affiliates/$id/referrals'
    | '/industry/$slug/$section'
    | '/packs/$group/$slug'
    | '/portal/apply/$group/$slug'
    | '/industry/$slug'
    | '/api/public/inbound/leads/$tenantSlug'
    | '/api/public/inbound/meta/$tenantSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/contact'
    | '/dsa-crm'
    | '/features'
    | '/industries'
    | '/landing-pages'
    | '/pricing'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/admin-packs'
    | '/_authenticated/affiliates'
    | '/_authenticated/ai'
    | '/_authenticated/audit-logs'
    | '/_authenticated/automation'
    | '/_authenticated/calendar'
    | '/_authenticated/choose-industry'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/digiverify'
    | '/_authenticated/feature-matrix'
    | '/_authenticated/fintech'
    | '/_authenticated/inbound'
    | '/_authenticated/it'
    | '/_authenticated/landing-analytics'
    | '/_authenticated/landing-conversions'
    | '/_authenticated/lead-sources'
    | '/_authenticated/leads'
    | '/_authenticated/meetings'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/partner'
    | '/_authenticated/payout-history'
    | '/_authenticated/pipeline'
    | '/_authenticated/portal'
    | '/_authenticated/productsales'
    | '/_authenticated/proposals'
    | '/_authenticated/realestate'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/settings-cms'
    | '/_authenticated/settings-pack'
    | '/_authenticated/settings-plans'
    | '/_authenticated/settings-tenants'
    | '/_authenticated/tasks'
    | '/_authenticated/tenant-billing'
    | '/_authenticated/tenant-dashboard'
    | '/_authenticated/tenant-portal'
    | '/_authenticated/tickets'
    | '/_authenticated/webhook-dead-letter'
    | '/_authenticated/webhook-settings'
    | '/blog/$slug'
    | '/campaign/$slug'
    | '/industries/$group'
    | '/p/$slug'
    | '/portal/$tenantSlug'
    | '/products/$slug'
    | '/t/$tenantSlug'
    | '/blog/'
    | '/industries/'
    | '/products/'
    | '/_authenticated/fintech/applications'
    | '/_authenticated/fintech/commissions'
    | '/_authenticated/fintech/lenders'
    | '/_authenticated/fintech/pipeline'
    | '/_authenticated/industry/$slug'
    | '/_authenticated/it/pipeline'
    | '/_authenticated/it/projects'
    | '/_authenticated/it/tickets'
    | '/_authenticated/productsales/commissions'
    | '/_authenticated/productsales/orders'
    | '/_authenticated/productsales/products'
    | '/_authenticated/realestate/clients'
    | '/_authenticated/realestate/pipeline'
    | '/_authenticated/realestate/properties'
    | '/_authenticated/tickets_/$id'
    | '/api/public/role-pdf'
    | '/industries/$group/$slug'
    | '/_authenticated/fintech/'
    | '/_authenticated/it/'
    | '/_authenticated/packs/'
    | '/_authenticated/productsales/'
    | '/_authenticated/realestate/'
    | '/industries/$group/'
    | '/_authenticated/affiliates_/$id/referrals'
    | '/_authenticated/industry/$slug/$section'
    | '/_authenticated/packs/$group/$slug'
    | '/portal/apply/$group/$slug'
    | '/_authenticated/industry/$slug/'
    | '/api/public/inbound/leads/$tenantSlug'
    | '/api/public/inbound/meta/$tenantSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DsaCrmRoute: typeof DsaCrmRoute
  FeaturesRoute: typeof FeaturesRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  LandingPagesRoute: typeof LandingPagesRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CampaignSlugRoute: typeof CampaignSlugRoute
  PSlugRoute: typeof PSlugRoute
  PortalTenantSlugRoute: typeof PortalTenantSlugRoute
  TTenantSlugRoute: typeof TTenantSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicRolePdfRoute: typeof ApiPublicRolePdfRoute
  PortalApplyGroupSlugRoute: typeof PortalApplyGroupSlugRoute
  ApiPublicInboundLeadsTenantSlugRoute: typeof ApiPublicInboundLeadsTenantSlugRoute
  ApiPublicInboundMetaTenantSlugRoute: typeof ApiPublicInboundMetaTenantSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-pages': {
      id: '/landing-pages'
      path: '/landing-pages'
      fullPath: '/landing-pages'
      preLoaderRoute: typeof LandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa-crm': {
      id: '/dsa-crm'
      path: '/dsa-crm'
      fullPath: '/dsa-crm'
      preLoaderRoute: typeof DsaCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/portal/$tenantSlug': {
      id: '/portal/$tenantSlug'
      path: '/portal/$tenantSlug'
      fullPath: '/portal/$tenantSlug'
      preLoaderRoute: typeof PortalTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$group': {
      id: '/industries/$group'
      path: '/$group'
      fullPath: '/industries/$group'
      preLoaderRoute: typeof IndustriesGroupRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/campaign/$slug': {
      id: '/campaign/$slug'
      path: '/campaign/$slug'
      fullPath: '/campaign/$slug'
      preLoaderRoute: typeof CampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/webhook-settings': {
      id: '/_authenticated/webhook-settings'
      path: '/webhook-settings'
      fullPath: '/webhook-settings'
      preLoaderRoute: typeof AuthenticatedWebhookSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhook-dead-letter': {
      id: '/_authenticated/webhook-dead-letter'
      path: '/webhook-dead-letter'
      fullPath: '/webhook-dead-letter'
      preLoaderRoute: typeof AuthenticatedWebhookDeadLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant-portal': {
      id: '/_authenticated/tenant-portal'
      path: '/tenant-portal'
      fullPath: '/tenant-portal'
      preLoaderRoute: typeof AuthenticatedTenantPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant-dashboard': {
      id: '/_authenticated/tenant-dashboard'
      path: '/tenant-dashboard'
      fullPath: '/tenant-dashboard'
      preLoaderRoute: typeof AuthenticatedTenantDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant-billing': {
      id: '/_authenticated/tenant-billing'
      path: '/tenant-billing'
      fullPath: '/tenant-billing'
      preLoaderRoute: typeof AuthenticatedTenantBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings-tenants': {
      id: '/_authenticated/settings-tenants'
      path: '/settings-tenants'
      fullPath: '/settings-tenants'
      preLoaderRoute: typeof AuthenticatedSettingsTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings-plans': {
      id: '/_authenticated/settings-plans'
      path: '/settings-plans'
      fullPath: '/settings-plans'
      preLoaderRoute: typeof AuthenticatedSettingsPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings-pack': {
      id: '/_authenticated/settings-pack'
      path: '/settings-pack'
      fullPath: '/settings-pack'
      preLoaderRoute: typeof AuthenticatedSettingsPackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings-cms': {
      id: '/_authenticated/settings-cms'
      path: '/settings-cms'
      fullPath: '/settings-cms'
      preLoaderRoute: typeof AuthenticatedSettingsCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/realestate': {
      id: '/_authenticated/realestate'
      path: '/realestate'
      fullPath: '/realestate'
      preLoaderRoute: typeof AuthenticatedRealestateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productsales': {
      id: '/_authenticated/productsales'
      path: '/productsales'
      fullPath: '/productsales'
      preLoaderRoute: typeof AuthenticatedProductsalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payout-history': {
      id: '/_authenticated/payout-history'
      path: '/payout-history'
      fullPath: '/payout-history'
      preLoaderRoute: typeof AuthenticatedPayoutHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lead-sources': {
      id: '/_authenticated/lead-sources'
      path: '/lead-sources'
      fullPath: '/lead-sources'
      preLoaderRoute: typeof AuthenticatedLeadSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing-conversions': {
      id: '/_authenticated/landing-conversions'
      path: '/landing-conversions'
      fullPath: '/landing-conversions'
      preLoaderRoute: typeof AuthenticatedLandingConversionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing-analytics': {
      id: '/_authenticated/landing-analytics'
      path: '/landing-analytics'
      fullPath: '/landing-analytics'
      preLoaderRoute: typeof AuthenticatedLandingAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound': {
      id: '/_authenticated/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof AuthenticatedInboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fintech': {
      id: '/_authenticated/fintech'
      path: '/fintech'
      fullPath: '/fintech'
      preLoaderRoute: typeof AuthenticatedFintechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feature-matrix': {
      id: '/_authenticated/feature-matrix'
      path: '/feature-matrix'
      fullPath: '/feature-matrix'
      preLoaderRoute: typeof AuthenticatedFeatureMatrixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/digiverify': {
      id: '/_authenticated/digiverify'
      path: '/digiverify'
      fullPath: '/digiverify'
      preLoaderRoute: typeof AuthenticatedDigiverifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose-industry': {
      id: '/_authenticated/choose-industry'
      path: '/choose-industry'
      fullPath: '/choose-industry'
      preLoaderRoute: typeof AuthenticatedChooseIndustryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliates': {
      id: '/_authenticated/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AuthenticatedAffiliatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-packs': {
      id: '/_authenticated/admin-packs'
      path: '/admin-packs'
      fullPath: '/admin-packs'
      preLoaderRoute: typeof AuthenticatedAdminPacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/industries/$group/': {
      id: '/industries/$group/'
      path: '/'
      fullPath: '/industries/$group/'
      preLoaderRoute: typeof IndustriesGroupIndexRouteImport
      parentRoute: typeof IndustriesGroupRoute
    }
    '/_authenticated/realestate/': {
      id: '/_authenticated/realestate/'
      path: '/'
      fullPath: '/realestate/'
      preLoaderRoute: typeof AuthenticatedRealestateIndexRouteImport
      parentRoute: typeof AuthenticatedRealestateRoute
    }
    '/_authenticated/productsales/': {
      id: '/_authenticated/productsales/'
      path: '/'
      fullPath: '/productsales/'
      preLoaderRoute: typeof AuthenticatedProductsalesIndexRouteImport
      parentRoute: typeof AuthenticatedProductsalesRoute
    }
    '/_authenticated/packs/': {
      id: '/_authenticated/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof AuthenticatedPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/it/': {
      id: '/_authenticated/it/'
      path: '/'
      fullPath: '/it/'
      preLoaderRoute: typeof AuthenticatedItIndexRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/fintech/': {
      id: '/_authenticated/fintech/'
      path: '/'
      fullPath: '/fintech/'
      preLoaderRoute: typeof AuthenticatedFintechIndexRouteImport
      parentRoute: typeof AuthenticatedFintechRoute
    }
    '/industries/$group/$slug': {
      id: '/industries/$group/$slug'
      path: '/$slug'
      fullPath: '/industries/$group/$slug'
      preLoaderRoute: typeof IndustriesGroupSlugRouteImport
      parentRoute: typeof IndustriesGroupRoute
    }
    '/api/public/role-pdf': {
      id: '/api/public/role-pdf'
      path: '/api/public/role-pdf'
      fullPath: '/api/public/role-pdf'
      preLoaderRoute: typeof ApiPublicRolePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets_/$id': {
      id: '/_authenticated/tickets_/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/realestate/properties': {
      id: '/_authenticated/realestate/properties'
      path: '/properties'
      fullPath: '/realestate/properties'
      preLoaderRoute: typeof AuthenticatedRealestatePropertiesRouteImport
      parentRoute: typeof AuthenticatedRealestateRoute
    }
    '/_authenticated/realestate/pipeline': {
      id: '/_authenticated/realestate/pipeline'
      path: '/pipeline'
      fullPath: '/realestate/pipeline'
      preLoaderRoute: typeof AuthenticatedRealestatePipelineRouteImport
      parentRoute: typeof AuthenticatedRealestateRoute
    }
    '/_authenticated/realestate/clients': {
      id: '/_authenticated/realestate/clients'
      path: '/clients'
      fullPath: '/realestate/clients'
      preLoaderRoute: typeof AuthenticatedRealestateClientsRouteImport
      parentRoute: typeof AuthenticatedRealestateRoute
    }
    '/_authenticated/productsales/products': {
      id: '/_authenticated/productsales/products'
      path: '/products'
      fullPath: '/productsales/products'
      preLoaderRoute: typeof AuthenticatedProductsalesProductsRouteImport
      parentRoute: typeof AuthenticatedProductsalesRoute
    }
    '/_authenticated/productsales/orders': {
      id: '/_authenticated/productsales/orders'
      path: '/orders'
      fullPath: '/productsales/orders'
      preLoaderRoute: typeof AuthenticatedProductsalesOrdersRouteImport
      parentRoute: typeof AuthenticatedProductsalesRoute
    }
    '/_authenticated/productsales/commissions': {
      id: '/_authenticated/productsales/commissions'
      path: '/commissions'
      fullPath: '/productsales/commissions'
      preLoaderRoute: typeof AuthenticatedProductsalesCommissionsRouteImport
      parentRoute: typeof AuthenticatedProductsalesRoute
    }
    '/_authenticated/it/tickets': {
      id: '/_authenticated/it/tickets'
      path: '/tickets'
      fullPath: '/it/tickets'
      preLoaderRoute: typeof AuthenticatedItTicketsRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/it/projects': {
      id: '/_authenticated/it/projects'
      path: '/projects'
      fullPath: '/it/projects'
      preLoaderRoute: typeof AuthenticatedItProjectsRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/it/pipeline': {
      id: '/_authenticated/it/pipeline'
      path: '/pipeline'
      fullPath: '/it/pipeline'
      preLoaderRoute: typeof AuthenticatedItPipelineRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/industry/$slug': {
      id: '/_authenticated/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof AuthenticatedIndustrySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fintech/pipeline': {
      id: '/_authenticated/fintech/pipeline'
      path: '/pipeline'
      fullPath: '/fintech/pipeline'
      preLoaderRoute: typeof AuthenticatedFintechPipelineRouteImport
      parentRoute: typeof AuthenticatedFintechRoute
    }
    '/_authenticated/fintech/lenders': {
      id: '/_authenticated/fintech/lenders'
      path: '/lenders'
      fullPath: '/fintech/lenders'
      preLoaderRoute: typeof AuthenticatedFintechLendersRouteImport
      parentRoute: typeof AuthenticatedFintechRoute
    }
    '/_authenticated/fintech/commissions': {
      id: '/_authenticated/fintech/commissions'
      path: '/commissions'
      fullPath: '/fintech/commissions'
      preLoaderRoute: typeof AuthenticatedFintechCommissionsRouteImport
      parentRoute: typeof AuthenticatedFintechRoute
    }
    '/_authenticated/fintech/applications': {
      id: '/_authenticated/fintech/applications'
      path: '/applications'
      fullPath: '/fintech/applications'
      preLoaderRoute: typeof AuthenticatedFintechApplicationsRouteImport
      parentRoute: typeof AuthenticatedFintechRoute
    }
    '/_authenticated/industry/$slug/': {
      id: '/_authenticated/industry/$slug/'
      path: '/'
      fullPath: '/industry/$slug/'
      preLoaderRoute: typeof AuthenticatedIndustrySlugIndexRouteImport
      parentRoute: typeof AuthenticatedIndustrySlugRoute
    }
    '/portal/apply/$group/$slug': {
      id: '/portal/apply/$group/$slug'
      path: '/portal/apply/$group/$slug'
      fullPath: '/portal/apply/$group/$slug'
      preLoaderRoute: typeof PortalApplyGroupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/packs/$group/$slug': {
      id: '/_authenticated/packs/$group/$slug'
      path: '/packs/$group/$slug'
      fullPath: '/packs/$group/$slug'
      preLoaderRoute: typeof AuthenticatedPacksGroupSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/$slug/$section': {
      id: '/_authenticated/industry/$slug/$section'
      path: '/$section'
      fullPath: '/industry/$slug/$section'
      preLoaderRoute: typeof AuthenticatedIndustrySlugSectionRouteImport
      parentRoute: typeof AuthenticatedIndustrySlugRoute
    }
    '/_authenticated/affiliates_/$id/referrals': {
      id: '/_authenticated/affiliates_/$id/referrals'
      path: '/affiliates/$id/referrals'
      fullPath: '/affiliates/$id/referrals'
      preLoaderRoute: typeof AuthenticatedAffiliatesIdReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/inbound/meta/$tenantSlug': {
      id: '/api/public/inbound/meta/$tenantSlug'
      path: '/api/public/inbound/meta/$tenantSlug'
      fullPath: '/api/public/inbound/meta/$tenantSlug'
      preLoaderRoute: typeof ApiPublicInboundMetaTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound/leads/$tenantSlug': {
      id: '/api/public/inbound/leads/$tenantSlug'
      path: '/api/public/inbound/leads/$tenantSlug'
      fullPath: '/api/public/inbound/leads/$tenantSlug'
      preLoaderRoute: typeof ApiPublicInboundLeadsTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedFintechRouteChildren {
  AuthenticatedFintechApplicationsRoute: typeof AuthenticatedFintechApplicationsRoute
  AuthenticatedFintechCommissionsRoute: typeof AuthenticatedFintechCommissionsRoute
  AuthenticatedFintechLendersRoute: typeof AuthenticatedFintechLendersRoute
  AuthenticatedFintechPipelineRoute: typeof AuthenticatedFintechPipelineRoute
  AuthenticatedFintechIndexRoute: typeof AuthenticatedFintechIndexRoute
}

const AuthenticatedFintechRouteChildren: AuthenticatedFintechRouteChildren = {
  AuthenticatedFintechApplicationsRoute: AuthenticatedFintechApplicationsRoute,
  AuthenticatedFintechCommissionsRoute: AuthenticatedFintechCommissionsRoute,
  AuthenticatedFintechLendersRoute: AuthenticatedFintechLendersRoute,
  AuthenticatedFintechPipelineRoute: AuthenticatedFintechPipelineRoute,
  AuthenticatedFintechIndexRoute: AuthenticatedFintechIndexRoute,
}

const AuthenticatedFintechRouteWithChildren =
  AuthenticatedFintechRoute._addFileChildren(AuthenticatedFintechRouteChildren)

interface AuthenticatedItRouteChildren {
  AuthenticatedItPipelineRoute: typeof AuthenticatedItPipelineRoute
  AuthenticatedItProjectsRoute: typeof AuthenticatedItProjectsRoute
  AuthenticatedItTicketsRoute: typeof AuthenticatedItTicketsRoute
  AuthenticatedItIndexRoute: typeof AuthenticatedItIndexRoute
}

const AuthenticatedItRouteChildren: AuthenticatedItRouteChildren = {
  AuthenticatedItPipelineRoute: AuthenticatedItPipelineRoute,
  AuthenticatedItProjectsRoute: AuthenticatedItProjectsRoute,
  AuthenticatedItTicketsRoute: AuthenticatedItTicketsRoute,
  AuthenticatedItIndexRoute: AuthenticatedItIndexRoute,
}

const AuthenticatedItRouteWithChildren = AuthenticatedItRoute._addFileChildren(
  AuthenticatedItRouteChildren,
)

interface AuthenticatedProductsalesRouteChildren {
  AuthenticatedProductsalesCommissionsRoute: typeof AuthenticatedProductsalesCommissionsRoute
  AuthenticatedProductsalesOrdersRoute: typeof AuthenticatedProductsalesOrdersRoute
  AuthenticatedProductsalesProductsRoute: typeof AuthenticatedProductsalesProductsRoute
  AuthenticatedProductsalesIndexRoute: typeof AuthenticatedProductsalesIndexRoute
}

const AuthenticatedProductsalesRouteChildren: AuthenticatedProductsalesRouteChildren =
  {
    AuthenticatedProductsalesCommissionsRoute:
      AuthenticatedProductsalesCommissionsRoute,
    AuthenticatedProductsalesOrdersRoute: AuthenticatedProductsalesOrdersRoute,
    AuthenticatedProductsalesProductsRoute:
      AuthenticatedProductsalesProductsRoute,
    AuthenticatedProductsalesIndexRoute: AuthenticatedProductsalesIndexRoute,
  }

const AuthenticatedProductsalesRouteWithChildren =
  AuthenticatedProductsalesRoute._addFileChildren(
    AuthenticatedProductsalesRouteChildren,
  )

interface AuthenticatedRealestateRouteChildren {
  AuthenticatedRealestateClientsRoute: typeof AuthenticatedRealestateClientsRoute
  AuthenticatedRealestatePipelineRoute: typeof AuthenticatedRealestatePipelineRoute
  AuthenticatedRealestatePropertiesRoute: typeof AuthenticatedRealestatePropertiesRoute
  AuthenticatedRealestateIndexRoute: typeof AuthenticatedRealestateIndexRoute
}

const AuthenticatedRealestateRouteChildren: AuthenticatedRealestateRouteChildren =
  {
    AuthenticatedRealestateClientsRoute: AuthenticatedRealestateClientsRoute,
    AuthenticatedRealestatePipelineRoute: AuthenticatedRealestatePipelineRoute,
    AuthenticatedRealestatePropertiesRoute:
      AuthenticatedRealestatePropertiesRoute,
    AuthenticatedRealestateIndexRoute: AuthenticatedRealestateIndexRoute,
  }

const AuthenticatedRealestateRouteWithChildren =
  AuthenticatedRealestateRoute._addFileChildren(
    AuthenticatedRealestateRouteChildren,
  )

interface AuthenticatedIndustrySlugRouteChildren {
  AuthenticatedIndustrySlugSectionRoute: typeof AuthenticatedIndustrySlugSectionRoute
  AuthenticatedIndustrySlugIndexRoute: typeof AuthenticatedIndustrySlugIndexRoute
}

const AuthenticatedIndustrySlugRouteChildren: AuthenticatedIndustrySlugRouteChildren =
  {
    AuthenticatedIndustrySlugSectionRoute:
      AuthenticatedIndustrySlugSectionRoute,
    AuthenticatedIndustrySlugIndexRoute: AuthenticatedIndustrySlugIndexRoute,
  }

const AuthenticatedIndustrySlugRouteWithChildren =
  AuthenticatedIndustrySlugRoute._addFileChildren(
    AuthenticatedIndustrySlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminPacksRoute: typeof AuthenticatedAdminPacksRoute
  AuthenticatedAffiliatesRoute: typeof AuthenticatedAffiliatesRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChooseIndustryRoute: typeof AuthenticatedChooseIndustryRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDigiverifyRoute: typeof AuthenticatedDigiverifyRoute
  AuthenticatedFeatureMatrixRoute: typeof AuthenticatedFeatureMatrixRoute
  AuthenticatedFintechRoute: typeof AuthenticatedFintechRouteWithChildren
  AuthenticatedInboundRoute: typeof AuthenticatedInboundRoute
  AuthenticatedItRoute: typeof AuthenticatedItRouteWithChildren
  AuthenticatedLandingAnalyticsRoute: typeof AuthenticatedLandingAnalyticsRoute
  AuthenticatedLandingConversionsRoute: typeof AuthenticatedLandingConversionsRoute
  AuthenticatedLeadSourcesRoute: typeof AuthenticatedLeadSourcesRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedPayoutHistoryRoute: typeof AuthenticatedPayoutHistoryRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProductsalesRoute: typeof AuthenticatedProductsalesRouteWithChildren
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedRealestateRoute: typeof AuthenticatedRealestateRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSettingsCmsRoute: typeof AuthenticatedSettingsCmsRoute
  AuthenticatedSettingsPackRoute: typeof AuthenticatedSettingsPackRoute
  AuthenticatedSettingsPlansRoute: typeof AuthenticatedSettingsPlansRoute
  AuthenticatedSettingsTenantsRoute: typeof AuthenticatedSettingsTenantsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTenantBillingRoute: typeof AuthenticatedTenantBillingRoute
  AuthenticatedTenantDashboardRoute: typeof AuthenticatedTenantDashboardRoute
  AuthenticatedTenantPortalRoute: typeof AuthenticatedTenantPortalRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedWebhookDeadLetterRoute: typeof AuthenticatedWebhookDeadLetterRoute
  AuthenticatedWebhookSettingsRoute: typeof AuthenticatedWebhookSettingsRoute
  AuthenticatedIndustrySlugRoute: typeof AuthenticatedIndustrySlugRouteWithChildren
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
  AuthenticatedPacksIndexRoute: typeof AuthenticatedPacksIndexRoute
  AuthenticatedAffiliatesIdReferralsRoute: typeof AuthenticatedAffiliatesIdReferralsRoute
  AuthenticatedPacksGroupSlugRoute: typeof AuthenticatedPacksGroupSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminPacksRoute: AuthenticatedAdminPacksRoute,
  AuthenticatedAffiliatesRoute: AuthenticatedAffiliatesRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChooseIndustryRoute: AuthenticatedChooseIndustryRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDigiverifyRoute: AuthenticatedDigiverifyRoute,
  AuthenticatedFeatureMatrixRoute: AuthenticatedFeatureMatrixRoute,
  AuthenticatedFintechRoute: AuthenticatedFintechRouteWithChildren,
  AuthenticatedInboundRoute: AuthenticatedInboundRoute,
  AuthenticatedItRoute: AuthenticatedItRouteWithChildren,
  AuthenticatedLandingAnalyticsRoute: AuthenticatedLandingAnalyticsRoute,
  AuthenticatedLandingConversionsRoute: AuthenticatedLandingConversionsRoute,
  AuthenticatedLeadSourcesRoute: AuthenticatedLeadSourcesRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedPayoutHistoryRoute: AuthenticatedPayoutHistoryRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProductsalesRoute: AuthenticatedProductsalesRouteWithChildren,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedRealestateRoute: AuthenticatedRealestateRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSettingsCmsRoute: AuthenticatedSettingsCmsRoute,
  AuthenticatedSettingsPackRoute: AuthenticatedSettingsPackRoute,
  AuthenticatedSettingsPlansRoute: AuthenticatedSettingsPlansRoute,
  AuthenticatedSettingsTenantsRoute: AuthenticatedSettingsTenantsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTenantBillingRoute: AuthenticatedTenantBillingRoute,
  AuthenticatedTenantDashboardRoute: AuthenticatedTenantDashboardRoute,
  AuthenticatedTenantPortalRoute: AuthenticatedTenantPortalRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedWebhookDeadLetterRoute: AuthenticatedWebhookDeadLetterRoute,
  AuthenticatedWebhookSettingsRoute: AuthenticatedWebhookSettingsRoute,
  AuthenticatedIndustrySlugRoute: AuthenticatedIndustrySlugRouteWithChildren,
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
  AuthenticatedPacksIndexRoute: AuthenticatedPacksIndexRoute,
  AuthenticatedAffiliatesIdReferralsRoute:
    AuthenticatedAffiliatesIdReferralsRoute,
  AuthenticatedPacksGroupSlugRoute: AuthenticatedPacksGroupSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface IndustriesGroupRouteChildren {
  IndustriesGroupSlugRoute: typeof IndustriesGroupSlugRoute
  IndustriesGroupIndexRoute: typeof IndustriesGroupIndexRoute
}

const IndustriesGroupRouteChildren: IndustriesGroupRouteChildren = {
  IndustriesGroupSlugRoute: IndustriesGroupSlugRoute,
  IndustriesGroupIndexRoute: IndustriesGroupIndexRoute,
}

const IndustriesGroupRouteWithChildren = IndustriesGroupRoute._addFileChildren(
  IndustriesGroupRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesGroupRoute: typeof IndustriesGroupRouteWithChildren
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesGroupRoute: IndustriesGroupRouteWithChildren,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DsaCrmRoute: DsaCrmRoute,
  FeaturesRoute: FeaturesRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  LandingPagesRoute: LandingPagesRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  CampaignSlugRoute: CampaignSlugRoute,
  PSlugRoute: PSlugRoute,
  PortalTenantSlugRoute: PortalTenantSlugRoute,
  TTenantSlugRoute: TTenantSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicRolePdfRoute: ApiPublicRolePdfRoute,
  PortalApplyGroupSlugRoute: PortalApplyGroupSlugRoute,
  ApiPublicInboundLeadsTenantSlugRoute: ApiPublicInboundLeadsTenantSlugRoute,
  ApiPublicInboundMetaTenantSlugRoute: ApiPublicInboundMetaTenantSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
